version: "3"
services:
  apigateway:
    build: "./apigateway"

    depends_on:
      - listing-service
      - user-service
    ports:
      - 7000:7000
    volumes:
      - ./apigateway:/opt/app

  listing-service:
    build: "./listing-service"
    environment:
      - DB_URI=mysql://root:password@listing-service-db/db?charset=UTF8
    depends_on:
      - listing-service-db
    ports:
      - 7100:7100
    volumes:
      - ./listing-service:/opt/app

  listing-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7200:3306

  user-service:
    build: "./user-service"
    depends_on:
      - user-service-db
    volumes:
      - ./user-service:/opt/app
    environment:
      - DB_URI=mysql://root:password@user-service-db/db?charset=UTF8
    ports:
      - 7101:7101

  user-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7201:3306
  # classfeild-service:
  # build: "./classfeild-service"
  # depends_on:
  # - classfeild-service-db
  # volumes:
  #     - ./classfeild-service:/opt/app
